import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 style={{textAlign:"center"}}>Next Js Project </h1>
          <div className="header">
            <Link href={"/"}>
              <button>Home</button>
            </Link>
            <Link href={"/posts"}>
              <button>Post</button>
            </Link>
            <Link href={"/ariticels"}>
                <button>Ariticel</button>
            </Link>
         </div>
         {children}
        </body>
      
    </html>
  );
}
